spring.application.name=Internship-Management
spring.datasource.url= jdbc:postgresql://localhost:5432/internship-management-db
spring.datasource.username = postgres
spring.datasource.password = 1234
#JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
#Logging
#Active Profile
spring.profiles.active=dev
#DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
#JWT
jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFy
jwt.expiration-ms=86400000